'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18051
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Battlefield_3___Help_Tool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _256250_10150976825778445_478537776_o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("256250_10150976825778445_478537776_o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _283387() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("283387", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _870mc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("870mc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _93() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("93", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _93R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("93R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property a_91() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("a-91", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aek_971() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aek-971", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ak74() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ak74", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property aks74u() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aks74u", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property an94() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("an94", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property asval() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asval", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_a10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-a10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_aav() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-aav", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_armored_kill___armored_shield_map___screen_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield_3_armored_kill_-_armored_shield_map_-_screen_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_bmp2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-bmp2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_boat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-boat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_btr_90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-btr-90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_cobra_8_620x348() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-cobra-8-620x348", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_dpv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-dpv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_f18_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-f18-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_f35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-f35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_huey_1_620x348() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-huey-1-620x348", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_humvee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-humvee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_ka60_5_620x348() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-ka60-5-620x348", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_lav_ad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-lav-ad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_lav25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-lav25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_mi_28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-mi-28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_su35_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-su35-large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_su39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-su39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_t90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-t90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_tunguska() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-tunguska", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_vdv1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-vdv1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_vodnik() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-vodnik", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_wallpaper_high_res1_original() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-wallpaper-high-res1_original", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property battlefield_3_z11_8_620x348() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battlefield-3-z11-8-620x348", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bf3_dogtags_all_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bf3-dogtags-all-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bf3_heli_sm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bf3_heli_sm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bf3_littlebird() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bf3-littlebird", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BF3_Weapons_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BF3-Weapons-Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property btr90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btr90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dao_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dao-12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property deletered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("deletered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dislike() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dislike", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dpv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dpv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f2000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f2000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fa18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fa18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property g36c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g36c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property growler_itv() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("growler itv", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property growler_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("growler-small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property humvee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("humvee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property igla() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("igla", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property javelin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("javelin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ka60() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ka60", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kh2002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kh2002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lav_ad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lav-ad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lav25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lav25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m1_abrams() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m1 abrams", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m1014() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m1014", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m16a3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m16a3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m16a4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m16a4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m1911() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m1911", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m1abrams() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m1abrams", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m249() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m249", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m27_iar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m27 iar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m40a5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m40a5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m416() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m416", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m4a1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m4a1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m60e4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m60e4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property m98b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("m98b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magnum() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magnum", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mi28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mi28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mk11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mk11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mp443() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mp443", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mp7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mp7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newspaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newspaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property p90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0003() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0003", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0005() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0005", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0006() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0006", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0009() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0009", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0012() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0012", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0014() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0014", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0017() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0017", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0018() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0018", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0019() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0019", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0020() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0020", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0021() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0021", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0022() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0022", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0023() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0023", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0025() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0025", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0026() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0026", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0027() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0027", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0028() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0028", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0029() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0029", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0031() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0031", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0032() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0032", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0033() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0033", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0034() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0034", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0035() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0035", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0036() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0036", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0037() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0037", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0038() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0038", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0039() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0039", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0040() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0040", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0041() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0041", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0042() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0042", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0043() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0043", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0044() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0044", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0045() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0045", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0046() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0046", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0047() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0047", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0048() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0048", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0049() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0049", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0051() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0051", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0052() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0052", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0053() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0053", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0054() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0054", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0055() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0055", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0056() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0056", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0057() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0057", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0058() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0058", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0059() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0059", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0060() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0060", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0061() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0061", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0062() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0062", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0063() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0063", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0064() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0064", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0065() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0065", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0066() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0066", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0067() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0067", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0068() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0068", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0069() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0069", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0070() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0070", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0071() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0071", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0072() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0072", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0073() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0073", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0074() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0074", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0075() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0075", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property page0076() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page0076", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdwr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdwr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pkp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pkp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pp200_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pp200+", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rex() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rex", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rhib() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rhib", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rpg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rpg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rpk_74m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rpk-74m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property saiga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saiga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scarh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scarh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sg553() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sg553", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property smaw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smaw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stinger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stinger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property su35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("su35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property su39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("su39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sv98() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sv98", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property svd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("svd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property t90() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("t90", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tunguska() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tunguska", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property type_88() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("type 88", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ump45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ump45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property usas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vdv_buggy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vdv buggy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vodnik() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vodnik", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property z11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("z11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
